import React from 'react';

const EUBanksList = () => {
    const banksEurope = [
        'ABN AMRO Group',
        'AIB Group',
        'Alpha Bank',
        'Banca Mediolanum',
        'Banco BPM',
        'Bank of Ireland',
        'Bankinter',
        'Banque Cantonale Vaudoise',
        'Banque Populaire',
        'Barclays',
        'Bawag Group',
        'BBVA',
        'Belfius',
        'BNP Paribas',
        'BNP Paribas Fortis',
        'CaixaBank',
        'Caisse d\'Epargne',
        'Commerzbank',
        'Crédit Agricole',
        'Credit Suisse',
        'Danske Bank',
        'Deutsche Bank',
        'DZ Bank',
        'Erste Group Bank',
        'Handelsbanken',
        'HSBC Holdings',
        'ING DiBa',
        'ING Group',
        'Intesa Sanpaolo',
        'KBC Group',
        'La Banque Postale',
        'Lloyds Banking Group',
        'Millennium bcp',
        'Monte dei Paschi di Siena',
        'Nationwide Building Society',
        'Nordea Bank',
        'OTP Bank',
        'Piraeus Bank',
        'Raiffeisen Bank International',
        'Royal Bank of Scotland',
        'Santander',
        'Sberbank of Russia',
        'Skandinaviska Enskilda Banken',
        'Société Générale',
        'Standard Chartered',
        'Swedbank',
        'TSB Bank',
        'UBS Group',
        'UniCredit',
        'Autre',

    ];
    return banksEurope; // Retourner la liste triée des noms de pays
};

export default EUBanksList;
