import React from 'react';

const EUCountriesList = () => {
  const paysEurope = [
    'Albanie',
    'Allemagne',
    'Andorre',
    'Autriche',
    'Belgique',
    'Biélorussie',
    'Bosnie-Herzégovine',
    'Bulgarie',
    'Chypre',
    'Croatie',
    'Danemark',
    'Espagne',
    'Estonie',
    'Finlande',
    'France',
    'Grèce',
    'Hongrie',
    'Irlande',
    'Islande',
    'Italie',
    'Kosovo',
    'Lettonie',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'Macédoine du Nord',
    'Malte',
    'Moldavie',
    'Monaco',
    'Monténégro',
    'Norvège',
    'Pays-Bas',
    'Pologne',
    'Portugal',
    'Roumanie',
    'Royaume-Uni',
    'Russie',
    'République tchèque',
    'Saint-Marin',
    'Serbie',
    'Slovaquie',
    'Slovénie',
    'Switzerland',
    'Suède',
    'Ukraine',
  ];

  return paysEurope; // Retourner la liste triée des noms de pays
};

export default EUCountriesList;
